---
- name: Configure Teleport.
  template:
    src: teleport.yaml.j2
    dest: /etc/teleport.yaml
  notify: restart teleport

# - name: Upload SSL certificate.
#   copy:
#     src: "{{ item.name }}"
#     dest: "/var/lib/teleport/{{ item.dest_name }}"
#   loop:
#     - {name: ssl.crt, dest_name: webproxy_cert.pem}
#     - {name: ssl.key, dest_name: webproxy_key.pem}
#   when: teleport_proxy_enabled == true